//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_cafe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Bills = new HashSet<Bill>();
            this.BillInfoes = new HashSet<BillInfo>();
        }

        public int id { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập Username!")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập Password!")]
        [DataType(DataType.Password)]
        public string PassWord { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập FullName!")]
        public string FullName { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập Address!")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập Phone!")]
        public int Phone { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập idRole!")]
        public Nullable<int> idRole { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập status!")]
        public string status { get; set; }
        public string LoginErrorMessage { get; set; }

        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillInfo> BillInfoes { get; set; }
    }
}
