//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_cafe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillInfo
    {
        public int BillInfo_id { get; set; }
        public int idBill { get; set; }
        public int idFood { get; set; }
        public Nullable<int> idAccount { get; set; }
        public Nullable<int> idTable { get; set; }
        public int count { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Bill Bill { get; set; }
        public virtual Food Food { get; set; }
        public virtual TableFood TableFood { get; set; }
    }
}
